### ISSUE TITLE
Static WEB App image hosting

### ISSUE THREAD

**Issue by Beserrovsky** [WidestView/OOL-API#10]
# Hosting in API

I know it isn't an API issue, but i've been searching and it seems that storing even the static images in the assets folder of a react app is usually not a great idea, since the API will be deployed and mobile apps might use some of those images, i find it really undestandable to select hosting static images though the API deploy.

**Comment by figurantpp** [comment]
Seems fine to me, but I believe we should move things to the backend once most things are finished.

**Comment by Beserrovsky** [comment]
Not really worth it rn
