### ISSUE TITLE
Models inheriting foreign keys

### ISSUE THREAD

**Issue by Beserrovsky** [WidestView/OOL-API#8]
# The question

Is it better to keep individual ids for models that depends on another? For instance, if we **need** an `User` to create an `Employee` why don't use User's Id for Emloyee's as well?

## Visualization

- Situation 1:

![image](https://user-images.githubusercontent.com/49963588/130610881-47906bb0-40cc-42c3-857a-1630f8167a87.png)

- Situation 2:

![image](https://user-images.githubusercontent.com/49963588/130610908-42ad3f5b-cff0-4a94-8566-29c060a2f66e.png)

**Comment by Beserrovsky** [comment]
@figurantpp PR review please!

**Comment by figurantpp** [comment]
We will definitely want to do certain operations in the employee class, and keeping both separate IDs in the employee class will make it much easier to do those operation later, I'd go with the first scenario.

**Comment by Beserrovsky** [comment]
Yeah, I thought the same, but having only one ID make not only the DB slightly lighter but primordialy makes so that is ***very*** unlikely to have one employee with no user class created

**Comment by figurantpp** [comment]
Yeah, it makes sense, I guess we won't have many issues with this later on
